import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayout
  // Extende a interface do Layout da aplicação
  extends Readonly<{
    children: React.ReactNode;
  }> {}

// Algo mais externo da aplicação
export default function RootLayout({ children }: IRootLayout) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
